In [80]:
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.preprocessing import OneHotEncoder,MinMaxScaler, StandardScaler

df = pd.read_csv("./data/titanic_clean.csv")
df.head(5)

df.info()
df.isna().sum()

# df.info()

<class 'pandas.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  889 non-null    int64
 1   Survived     889 non-null    int64
 2   Pclass       889 non-null    int64
 3   Name         889 non-null    str
 4   Sex          889 non-null    str
 5   Age          889 non-null    float64
 6   SibSp        889 non-null    int64
 7   Parch        889 non-null    int64
 8   Ticket       889 non-null    str
 9   Fare         889 non-null    float64
 10  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(4)
memory usage: 76.5 KB

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [81]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Embarked           str
dtype: object

In [82]:
df.drop(columns=["PassengerId","Name","Ticket"], inplace=True)
df.head(5)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [83]:

df_str = df.select_dtypes(include="str")
cat_features = ["Sex","Embarked"]
# df_str.groupby("Embarked").
one_hot_encoder =OneHotEncoder( sparse_output=False, handle_unknown="ignore")
one_hot_encoder_sp =OneHotEncoder( sparse_output=True, handle_unknown="ignore")

one_hot_encoder.fit(df[cat_features])
one_hot_encoder_sp.fit(df[cat_features])
one_hot_encoder

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [84]:
colums_features = one_hot_encoder.get_feature_names_out(cat_features)
colums_features_sp = one_hot_encoder_sp.get_feature_names_out(cat_features)
colums_features
# type(colums_features)

array(['Sex_female', 'Sex_male', 'Embarked_C', 'Embarked_Q', 'Embarked_S'],
      dtype=object)

In [85]:
transformed_categorical_features = one_hot_encoder.transform(df[cat_features])
transformed_categorical_features_sp = one_hot_encoder_sp.transform(df[cat_features])
transformed_categorical_features

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]], shape=(889, 5))

In [86]:
df_transformed_one_hot = pd.DataFrame(transformed_categorical_features, columns=colums_features)
df_transformed_one_hot_sp = pd.DataFrame.sparse.from_spmatrix(transformed_categorical_features_sp, columns=colums_features_sp)
df_transformed_one_hot.head(5)
df_transformed_one_hot_sp.head(5)
df_transformed_one_hot_sp.info()

<class 'pandas.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Sex_female  1 non-null      Sparse[float64, nan]
 1   Sex_male    1 non-null      Sparse[float64, nan]
 2   Embarked_C  1 non-null      Sparse[float64, nan]
 3   Embarked_Q  1 non-null      Sparse[float64, nan]
 4   Embarked_S  1 non-null      Sparse[float64, nan]
dtypes: Sparse[float64, nan](5)
memory usage: 21.0 KB

In [87]:
df.drop(columns= cat_features, inplace=True)
df_final = df.join(df_transformed_one_hot)
# df = pd.concat([df, df_transformed_one_hot], axis=1)
df_final.head(5)

   Survived  Pclass   Age  SibSp  ...  Sex_male  Embarked_C  Embarked_Q  Embarked_S
0         0       3  22.0      1  ...       1.0         0.0         0.0         1.0
1         1       1  38.0      1  ...       0.0         1.0         0.0         0.0
2         1       3  26.0      0  ...       0.0         0.0         0.0         1.0
3         1       1  35.0      1  ...       0.0         0.0         0.0         1.0
4         0       3  35.0      0  ...       1.0         0.0         0.0         1.0

[5 rows x 11 columns]

In [88]:
df_final.describe()

         Survived      Pclass         Age  ...  Embarked_C  Embarked_Q  Embarked_S
count  889.000000  889.000000  889.000000  ...  889.000000  889.000000  889.000000
mean     0.382452    2.311586   29.535624  ...    0.188976    0.086614    0.724409
std      0.486260    0.834700   14.527483  ...    0.391710    0.281427    0.447063
min      0.000000    1.000000    0.420000  ...    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.000000  ...    0.000000    0.000000    0.000000
50%      0.000000    3.000000   28.000000  ...    0.000000    0.000000    1.000000
75%      1.000000    3.000000   38.000000  ...    0.000000    0.000000    1.000000
max      1.000000    3.000000   80.000000  ...    1.000000    1.000000    1.000000

[8 rows x 11 columns]

In [89]:
colums_to_scale = ["Age","SibSp","Parch","Fare","Pclass"]
scaler = MinMaxScaler(clip=True)
scaler.fit(df[colums_to_scale])
# scaled_features = scaler.transform(df[colums_to_scale])
df_final[colums_to_scale] = scaler.fit_transform(df[colums_to_scale])
df_final.head(5)

   Survived  Pclass       Age  ...  Embarked_C  Embarked_Q  Embarked_S
0         0     1.0  0.271174  ...         0.0         0.0         1.0
1         1     0.0  0.472229  ...         1.0         0.0         0.0
2         1     1.0  0.321438  ...         0.0         0.0         1.0
3         1     0.0  0.434531  ...         0.0         0.0         1.0
4         0     1.0  0.434531  ...         0.0         0.0         1.0

[5 rows x 11 columns]

In [90]:
df_final.describe()

         Survived      Pclass         Age  ...  Embarked_C  Embarked_Q  Embarked_S
count  889.000000  889.000000  889.000000  ...  889.000000  889.000000  889.000000
mean     0.382452    0.655793    0.365866  ...    0.188976    0.086614    0.724409
std      0.486260    0.417350    0.182552  ...    0.391710    0.281427    0.447063
min      0.000000    0.000000    0.000000  ...    0.000000    0.000000    0.000000
25%      0.000000    0.500000    0.246042  ...    0.000000    0.000000    0.000000
50%      0.000000    1.000000    0.346569  ...    0.000000    0.000000    1.000000
75%      1.000000    1.000000    0.472229  ...    0.000000    0.000000    1.000000
max      1.000000    1.000000    1.000000  ...    1.000000    1.000000    1.000000

[8 rows x 11 columns]

In [91]:
scaler.transform([[3,1,0,7.10,3]])

/Users/qiyunge/winMac/SoftwareDev/LaselleCollege/3_C2_apprentissage_automatique_et_réseaux_de_neurones/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(

array([[0.03242021, 0.125     , 0.        , 0.01385828, 1.        ]])